apiVersion: v1
kind: Pod
metadata:
  name: dra-test-pod
spec:
  resourceClaims:
    - name: nvidia-gpu
      resourceClaimTemplateName: nvidia-gpu-claim-template
  containers:
    - name: test
      #image: busybox
      #command: ["echo", "DRA claim worked"]
      image: ubuntu:22.04
      command: ["bash", "-c"]
      args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
      resources:
        claims:
          - name: nvidia-gpu
  restartPolicy: Never
